#ifndef FILTERPLUGINBLUR_GLOBAL_H
#define FILTERPLUGINBLUR_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(FILTERPLUGINBLUR_LIBRARY)
#  define FILTERPLUGINBLURSHARED_EXPORT Q_DECL_EXPORT
#else
#  define FILTERPLUGINBLURSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // FILTERPLUGINBLUR_GLOBAL_H
