#ifndef FILTERPLUGINGLOBAL_H
#define FILTERPLUGINGLOBAL_H

#include <QtCore/qglobal.h>

#if defined(FILTERPLUGINDESIGNER_LIBRARY)
#  define FILTERPLUGINDESIGNERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define FILTERPLUGINDESIGNERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // FILTERPLUGINGLOBAL_H
