#ifndef FILTERPLUGINORIGINAL_GLOBAL_H
#define FILTERPLUGINORIGINAL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(FILTERPLUGINORIGINAL_LIBRARY)
#  define FILTERPLUGINORIGINALSHARED_EXPORT Q_DECL_EXPORT
#else
#  define FILTERPLUGINORIGINALSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // FILTERPLUGINORIGINAL_GLOBAL_H
