#ifndef FILTERPLUGINGRAYSCALE_GLOBAL_H
#define FILTERPLUGINGRAYSCALE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(FILTERPLUGINGRAYSCALE_LIBRARY)
#  define FILTERPLUGINGRAYSCALESHARED_EXPORT Q_DECL_EXPORT
#else
#  define FILTERPLUGINGRAYSCALESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // FILTERPLUGINGRAYSCALE_GLOBAL_H
